# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad36684ac5394a219db6ccdbc2bf8a8caf31e527a3766cf1629f18dfdb3822e475f2e2749f3900161227b1d60342b2e94aeb6622828e4249b887e7e4b8475089

test:
  secret_key_base: 6e5acc80b86ebbaf234c701f02cd683d45f010ee2acd40e73c46298da3bd820fb0e9b761ee50f7fe10d0a4de50be8356d3e7bcd21d36c7ea2d3b574567cff2bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
